### PR TITLE
[WIP] Allow running platformio from git checkout

### PR DESCRIPTION
**Pull request by jrobeson**
This command will allow folks to run platformio directly from git checkout (assuming they have the dependencies installed)

I just did the basic work here to see if this was a wanted feature. I assume that the docs would need updated also.

Some sanity checking for libraries might be good too, if you can tell me what might be good enough

### CODE REVIEW

**Comment by ivankravets** [comment]
1. What is difference between "Development version"? http://docs.platformio.org/en/latest/installation.html#development-version
2. How user will know which dependent packages need to install?
3. I recommend to use `pip` directly. On GitHub page exists option "Download ZIP", you can use this link directly with `pip`. 

Another solution (editable package):
```
git clone https://github.com/platformio/platformio.git
pip install -e platformio
```

Now, you can use `git pull` to be up-to-date with the latest development version.

**Comment by ivankravets** [comment]
Also please look into [virtualenv](https://virtualenv.pypa.io/en/latest/index.html). It allows to multiple isolated environments with PlatformIO.

**Comment by jrobeson** [comment]
but with this, you don't have to pip install anything but the dependencies.. it just works. You don't have to remember to pip install everytime you update.

**Comment by ivankravets** [comment]
`pip` allows to have editable package mounted to specific directory, repo and etc. Try:
```shell
pip install -e /path/to/editable/directory
```

It will install correctly your package and allow you to code on it from the specific directory.

**Comment by jrobeson** [comment]
hmm, but why? what are the advantages over my 4 line script?

**Comment by jrobeson** [comment]
hmm, but why? what are the advantages over my 4 line script?

**Comment by jrobeson** [comment]
hmm, but why? what are the advantages over my 4 line script?

**Comment by jrobeson** [comment]
hmm, but why? what are the advantages over my 4 line script?

**Comment by jrobeson** [comment]
hmm, but why? what are the advantages over my 4 line script?

**Comment by jrobeson** [comment]
hmm, but why? what are the advantages over my 4 line script?

**Comment by jrobeson** [comment]
I just wanna be clear, I'm not really arguing about this to simply get my PR merged. It's OK if you don't like the philosophy of the way this would work. I wouldn't be upset at all if you chose not to merge it. However, I do want to truly want to know why your suggested methods are better.

**Comment by ivankravets** [comment]
Hmm... :disappointed: I can't understand your tone...

1. You look on PlatformIO from developer point
2. You understand what does mean `pip`
3. You know how to install required packages.

How about others?

My philosophy is based on [KISS principle](https://en.wikipedia.org/wiki/KISS_principle). PlatformIO is intended for the different user categories: electronic engineers, embedded hobbyists, students, teachers and etc. Most of them don't have Python installed, I'm not speech about "Python Fatal ImportException" which they will receive when run directly "bin" like you propose. 

PlatformIO auditory is very different and huge - https://twitter.com/platformio_org/status/640559285269831681 and PlatformIO should be easy for using and installing. 

When people see `bin/platformio` then it mean that this is LAUNCH POINT and all should work without any additional steps. It looks like click on `exe` file using Windows OS. However, this isn't truth. Need to take additional measures to understand what does mean Python's `ImportException` and how to resolve it.

So, more then 1 year I've been working on "Simplifying PlatformIO Installation Process", but not on "to messy users".

-----

`pip` is installed on the all Unix-based systems, on Windows is will be installed when user installs Python. It means, that we have unique "entrance point" as for "How to install PlatformIO". If you prefer to work with the latest `develop` branch (which isn't recommended for end-users), I recommend to work with [tox](https://testrun.org/tox/latest/). See [PlatformIO tox.ini](https://github.com/platformio/platformio/blob/develop/tox.ini). How does it work?

```shell
# don't forget to install tox `pip install tox`
➜  tmp  git clone https://github.com/platformio/platformio.git
Cloning into 'platformio'...
remote: Counting objects: 7475, done.
remote: Compressing objects: 100% (225/225), done.
remote: Total 7475 (delta 119), reused 0 (delta 0), pack-reused 7244
Receiving objects: 100% (7475/7475), 20.51 MiB | 1.73 MiB/s, done.
Resolving deltas: 100% (5097/5097), done.
Checking connectivity... done.
➜  tmp  cd platformio
➜  platformio git:(develop) tox -e develop
develop create: /private/tmp/platformio/.tox/develop
develop installdeps: isort, flake8
develop develop-inst: /private/tmp/platformio
develop installed: bottle==0.12.8,click==5.1,flake8==2.4.1,isort==4.1.2,lockfile==0.10.2,mccabe==0.3.1,pep8==1.5.7,-e git+https://github.com/platformio/platformio.git@ed5f035d1cac2f3f6afdb5a0a2cf191118e6ba23#egg=platformio-develop,pyflakes==0.8.1,pyserial==2.7,requests==2.7.0,scons==2.3.6,wheel==0.24.0
develop runtests: PYTHONHASHSEED='71931176'
develop runtests: commands[0] | python --version
Python 2.7.10
___________________________________________________________________________ summary ____________________________________________________________________________
  develop: commands succeeded
  congratulations :)
➜  platformio git:(develop) source .tox/develop/bin/activate
(develop)➜  platformio git:(develop) pip list
bottle (0.12.8)
click (5.1)
flake8 (2.4.1)
isort (4.1.2)
lockfile (0.10.2)
mccabe (0.3.1)
pep8 (1.5.7)
pip (7.1.2)
platformio (2.3.1, /private/tmp/platformio)
pyflakes (0.8.1)
pyserial (2.7)
requests (2.7.0)
scons (2.3.6)
setuptools (18.2)
wheel (0.24.0)
(develop)➜  platformio git:(develop) which platformio
/private/tmp/platformio/.tox/develop/bin/platformio
(develop)➜  platformio git:(develop) /private/tmp/platformio/.tox/develop/bin/platformio --version
PlatformIO, version 2.3.1
```

Now you can sync PlatformIO `develop` snapshot using `git pull` command:
```shell
(develop)➜  platformio git:(develop) git pull
Already up-to-date.
```

**Comment by ivankravets** [comment]
As for "I don't want to merge your PR". I'm grateful for all contributions, but it should be usable for all of us and should messy/break PlatformIO at all. Please take a look into history (https://github.com/platformio/platformio/commits?author=jrobeson) where I've merged your PR earlier.

**Comment by ivankravets** [comment]
Please reopen this pull-request if you still have any questions.

**Pull request closed without merging**
