### PR TITLE
added soft reboot to teensy_loader_cli

### PR DESCRIPTION
**Pull request by TimJay**
I added the soft reboot switch to the teensy_loader_cli, so that you don't have to press the reset button on the Teensy each time.

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks @TimJay! I will release it in 1.5.0 soon.

**Comment by TimJay** [comment]
@ivankravets I guess that was my mistake, this is based on release/v1.4.0 but it should be merged into master or develop

**Comment by ivankravets** [comment]
No here any mistakes :blush: I mean, that I've merged your contribution and it will be available in the next stable release (1.5.0). If you want to try ``develop`` version of PlatformIO please look into http://docs.platformio.org/en/latest/installation.html#development-version

**Comment by TimJay** [comment]
@ivankravets is there a way for you to remove this commit from the platformio:release/v1.4.0 branch? I see you merged it into the develop branch.

**Comment by ivankravets** [comment]
No, I can't remove it :( Sorry, I understand now what do you mean. I will be more careful next time. Please make your contributions to ``develop`` branch next time.

**Comment by TimJay** [comment]
@ivankravets if you still have the original platformio:release/v1.4.0 branch before my commit, you could force-push that. If you don't have that, you could do an interactive rebase to skip/delete my commit locally and then pushed the cleaned branch.

**Pull request merged**
