### PR TITLE
Support for TeensyLC

### PR DESCRIPTION
**Pull request by colincarter**
Hello, Here's a pull request for the Teensy LC (https://www.pjrc.com/teensy/teensyLC.html).  I hope I've covered everything.  It needs the ldscript file mkl26z64.ld but not sure how to include that here.

### CODE REVIEW

**Comment by ivankravets** [comment]
@colincarter thanks a lot for your contribution!

1. Do you have that board?
2. ``mkl26z64.ld`` we will ask @valeros to add it to ``ldscripts`` package, which is located in [home_dir](http://docs.platformio.org/en/latest/projectconf.html#home-dir)/packages/ldsripts
3. Has @PaulStoffregen finished with ``TeensyLC`` and ``Arduino`` framework? Is TeensyLC officially released with Arduino IDE?
4. @valeros please update package ``framework-arduinoteensy`` with this core https://github.com/PaulStoffregen/cores
5. How about uploading? Does ``Teensy CLI`` support all OS?

**Comment by colincarter** [comment]
Hi,

1. Yes I've got the board
2. I copied mkl26z64.ld from the Arduino hardware/teensy/avr/cores/teensy3 (on OS X) directory to home_dir/packages/ldscripts to test the build.
3. As far as I can see it's been officially released and comes bundled with the latest Teensy Loader Application.
5. I've used the Teensy Loader to upload with platformio run

**Comment by PaulStoffregen** [comment]
Regarding question 3: **YES**.  Teensy-LC was officially released on March 12.  Teensy-LC is now in stock at many major distributors, or of course can be ordered directly from PJRC.

https://www.sparkfun.com/products/13305
http://www.exp-tech.de/teensy-lc
https://www.adafruit.com/products/2419
http://www.hobbytronics.co.uk/teensy-lc?keyword=teensy

Teensyduino 1.21, the first non-beta version to support Teensy-LC, was released on March 15.

Teensyduino 1.22, primarily an update to support Arduino 1.6.2 & 1.6.3 (released within the last week) will be published later today.  Beta versions for 1.22 have been available for the last 5 days.

**Comment by ivankravets** [comment]
@valeros Please update ``framework-arduinoteensy`` and ``tool-teensy`` to the latest version for the all platforms.

**Pull request closed without merging**
