### PR TITLE
Update ststm32.json

### PR DESCRIPTION
**Pull request by dkuku**
added nucleo_f446re board
https://developer.mbed.org/platforms/ST-Nucleo-F446RE/

### CODE REVIEW

**Comment by ivankravets** [comment]
@valeros do we need to update `framework-mbed` package for it?

**Comment by dkuku** [comment]
the framework-mbed already supports this board:
kuku@kuku:$ cat .platformio/packages/framework-mbed/boards.txt |grep 446
NUCLEO_F446RE


-- 
Sincerely
Daniel Kukuła


2015-09-27 14:49 GMT+01:00 Ivan Kravets <notifications@github.com>:

**Comment by ivankravets** [comment]
@dkuku  Thanks a lot!

**Comment by dkuku** [comment]
Hi, today I had a little time to test it with platformio-develop/examples/mbed and this board.
The examples are compiling without problems but I see there is problem with uploading.
After the error you can see the output from latest stlink - compiled on ubuntu


kuku@klapa:~/workspace/stm32/platformio-develop/examples/mbed/mbed-serial$ platformio run --target upload
[Sat Oct  3 21:58:52 2015] Processing nucleo_f446re (upload_protocol: stlink, board: nucleo_f446re, framework: mbed, platform: ststm32)
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
arm-none-eabi-g++ -o .pioenvs/nucleo_f446re/src/main.o -c -std=gnu++98 -fno-rtti -fdata-sections -ffunction-sections -Wno-unused-parameter -fno-exceptions -Wextra -fno-delete-null-pointer-checks -fmessage-length=0 -mthumb -Wno-missing-field-initializers -c -fno-builtin -O2 -mfpu=fpv4-sp-d16 -fomit-frame-pointer -Wall -mfloat-abi=softfp -MMD -mcpu=cortex-m4 -DMBED_BUILD_TIMESTAMP=1441274016.69 -DTARGET_M4 -DTARGET_FF_ARDUINO -DTOOLCHAIN_GCC_ARM -DTOOLCHAIN_GCC -DTARGET_FF_MORPHO -DTARGET_CORTEX_M -D__FPU_PRESENT=1 -DTARGET_STM32F446RE -DTARGET_NUCLEO_F446RE -D__MBED__=1 -DTARGET_STM -DTARGET_STM32F4 -D__CORTEX_M4 -DARM_MATH_CM4 -DPLATFORMIO=020303 -I.pioenvs/nucleo_f446re/FrameworkMbedInc248832578 -I.pioenvs/nucleo_f446re/FrameworkMbedInc-213564679 -I.pioenvs/nucleo_f446re/FrameworkMbedInc-250686161 -I.pioenvs/nucleo_f446re/FrameworkMbedInc-1045879033 -I.pioenvs/nucleo_f446re/FrameworkMbedInc1212534662 -I.pioenvs/nucleo_f446re/FrameworkMbedInc1388569159 -I.pioenvs/nucleo_f446re/FrameworkMbedInc164271123 -I.pioenvs/nucleo_f446re/FrameworkMbedInc875717617 src/main.cpp
arm-none-eabi-ar rcs .pioenvs/nucleo_f446re/libFrameworkMbed.a @/tmp/pioarargs-f6e5de975c7e766c67aca8c2126800f2
arm-none-eabi-ranlib .pioenvs/nucleo_f446re/libFrameworkMbed.a
arm-none-eabi-g++ -o .pioenvs/nucleo_f446re/firmware.elf -Wl,--gc-sections -Wl,--wrap,main -mcpu=cortex-m4 -mthumb -mfpu=fpv4-sp-d16 -mfloat-abi=softfp --specs=nano.specs -u_printf_float -u_scanf_float -Wl,-T /home/kuku/.platformio/packages/framework-mbed/variant/NUCLEO_F446RE/mbed/TARGET_NUCLEO_F446RE/TOOLCHAIN_GCC_ARM/STM32F446XE.ld .pioenvs/nucleo_f446re/src/main.o -L/home/kuku/.platformio/packages/framework-mbed/variant/NUCLEO_F446RE/mbed/TARGET_NUCLEO_F446RE/TOOLCHAIN_GCC_ARM -L.pioenvs/nucleo_f446re -Wl,--start-group -lc -lgcc -lm -lstdc++ -lnosys -lsupc++ -lmbed -lc -lgcc -Wl,-whole-archive .pioenvs/nucleo_f446re/libFrameworkMbed.a -Wl,-no-whole-archive -Wl,--end-group
arm-none-eabi-objcopy -O binary .pioenvs/nucleo_f446re/firmware.elf .pioenvs/nucleo_f446re/firmware.bin
/home/kuku/.platformio/packages/tool-stlink/st-flash write .pioenvs/nucleo_f446re/firmware.bin 0x08000000
2015-10-03T21:58:53 INFO src/stlink-common.c: Loading device parameters....
2015-10-03T21:58:53 WARN src/stlink-common.c: unknown chip id! 0x10006421
scons: *** [upload] Error 255
=============================================================================== [ ERROR ] Took 1.58 seconds ===============================================================================
kuku@klapa:~/workspace/stm32/platformio-develop/examples/mbed/mbed-serial$ ~/workspace/stm32/stlink/st-flash write .pioenvs/nucleo_f446re/firmware.bin 0x08000000
2015-10-03T21:59:07 INFO src/stlink-common.c: Loading device parameters....
2015-10-03T21:59:07 INFO src/stlink-common.c: Device connected is: F446 device, id 0x10006421
2015-10-03T21:59:07 INFO src/stlink-common.c: SRAM size: 0x20000 bytes (128 KiB), Flash: 0x80000 bytes (512 KiB) in pages of 131072 bytes
2015-10-03T21:59:07 INFO src/stlink-common.c: Attempting to write 37536 (0x92a0) bytes to stm32 address: 134217728 (0x8000000)
EraseFlash - Sector:0x0 Size:0x4000
Flash page at addr: 0x08000000 erasedEraseFlash - Sector:0x1 Size:0x4000
Flash page at addr: 0x08004000 erasedEraseFlash - Sector:0x2 Size:0x4000
Flash page at addr: 0x08008000 erased
2015-10-03T21:59:08 INFO src/stlink-common.c: Finished erasing 3 pages of 16384 (0x4000) bytes
2015-10-03T21:59:08 INFO src/stlink-common.c: Starting Flash write for F2/F4/L4
2015-10-03T21:59:08 INFO src/stlink-common.c: Successfully loaded flash loader in sram
enabling 32-bit flash writes
size: 32768
size: 4768
2015-10-03T21:59:08 INFO src/stlink-common.c: Starting verification of write complete
2015-10-03T21:59:08 INFO src/stlink-common.c: Flash written and verified! jolly good!
kuku@klapa:~/workspace/stm32/platformio-develop/examples/mbed/mbed-serial$

**Comment by ivankravets** [comment]
@valeros could you retest it?

**Comment by valeros** [comment]
Hi @dkuku!
Please, try new st-link package via `platformio update`.

**Comment by dkuku** [comment]
Hi - now it works fine for my board - thanks

-- 
Sincerely
Daniel Kukuła


2015-10-05 19:57 GMT+01:00 Valeriy Koval <notifications@github.com>:

**Pull request merged**
