### PR TITLE
Emacs IDE integration support

### PR DESCRIPTION
**Pull request by ZachMassia**
As discussed on Gitter, I've completed the initial version of the project template, and also the minor mode for Emacs. 

I've also submitted a [PR](https://github.com/milkypostman/melpa/pull/3431) to the MELPA repo for Emacs to allow easy installation of the minor mode.

### CODE REVIEW

**Comment by ivankravets** [comment]
Thanks a lot for great PR! Could you provide screenshot like this http://docs.platformio.org/en/latest/ide/vim.html#screenshot ? People like pictures :smile: 

Happy Holidays and Merry Christmas!

**Comment by ZachMassia** [comment]
Thanks, Merry Christmas to you as well @ivankravets . 

I'll try and get a screenshot up and also fix the test error tonight.

**Comment by ivankravets** [comment]
Thanks! 

> and also fix the test error tonight.

Please edit [this file](https://raw.githubusercontent.com/platformio/platformio/develop/docs/ide.rst) with
```rst
.. toctree::
    :maxdepth: 2

    ide/arduino
    ide/atom
    ide/clion
    ide/eclipse
    ide/emacs
    ide/energia
    ide/qtcreator
    ide/sublimetext
    ide/vim
    ide/visualstudio
```

**Comment by crushedice2000** [comment]
Wow! PR number 404!

**Comment by ivankravets** [comment]
@crushedice2000 :smile:  :smile:  :smile:  NOT FOUND

Do you use Emacs?

**Comment by crushedice2000** [comment]
@ivankravets: No, I don't use emacs nor vim ;-) however would be great to add support for emacs ;-)

**Comment by ZachMassia** [comment]
Just got my Emacs package added into MELPA :)

Anything else you see that needs modification on the template side, @ivankravets ?

**Comment by ivankravets** [comment]
My congrats ! :)

Could you make a screenshot? See VIM integration in the docs for example. 

Thanks.

**Comment by ivankravets** [comment]
@ZachMassia Thanks a lot for this PR!!! Will be released with PlatformIO 2.7.0 which is planned on 2015-12-29

See http://docs.platformio.org/en/latest/ide/emacs.html

:christmas_tree: :gift: :christmas_tree: :gift: :christmas_tree: :gift: :christmas_tree: :gift:

**Comment by ZachMassia** [comment]
Awesome, glad I could help :+1:

**Pull request merged**
